name: github action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    steps:
      - name: 🗂️ checkout repository
        uses: actions/checkout@v3

      - name: ⏰ setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: 💻 setup java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 🔑 chmod gradlew
        run: chmod +x gradlew

      - name: 🧬 generate jar
        run: ./gradlew fatJar

      - name: 🪩 execute jar
        run: java -DACCESS_TOKEN=${{ env.ACCESS_TOKEN }} -jar ./build/libs/postingbox-all*.jar
